// <auto-generated />
namespace ProyectoFinal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class correccionesv2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(correccionesv2));
        
        string IMigrationMetadata.Id
        {
            get { return "201511201700451_correccionesv2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
